apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: Go_RunTimeNew
  janus-idp.io/tekton: Go_RunTimeNew
  backstage.io/kubernetes-id: Go_RunTimeNew
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: Go_RunTimeNew
resources:
- deployment.yaml
- route.yaml
- service.yaml
