apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: Go_RunTimeNew
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: Go_RunTimeNew 
  name: Go_RunTimeNew
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: Go_RunTimeNew
    weight: 100 
